### ISSUE TITLE
Create Install artisan command

### ISSUE THREAD

**Issue by heyitsbalazs** [getawait/await#2]
Inspiration: https://github.com/JeffreyWay/council/blob/master/app/Console/Commands/InstallCommand.php

**Comment by ricardobarantini** [comment]
Can I help the project resolving this issue?

**Comment by heyitsbalazs** [comment]
Hey @ricardobarantini,

That'd be great – mind you, the project is still in very very early stages. :) 

The above file should serve as a good starting point for creating a setup command. Should you wish to set things up on your computer manually in the meantime, feel free to do so, I've included some steps in the readme file.

Thanks 😊

**Comment by heyitsbalazs** [comment]
Feature added in #7
